language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - mkdir -p build/logs
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_success:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then travis_retry php vendor/bin/coveralls; fi
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then php vendor/bin/test-reporter --coverage-report ./build/logs/clover.xml; fi
